### ISSUE TITLE
android release apk keep crashing

### ISSUE THREAD

**Issue by iwanbk** [iwanbk/myceliumflut#26]
debug apk is fine.

The error
```java
E/AndroidRuntime(19100): FATAL EXCEPTION: main
E/AndroidRuntime(19100): Process: tech.threefold.mycelium, PID: 19100
E/AndroidRuntime(19100): java.lang.UnsatisfiedLinkError: Can't obtain peer field ID for class com.sun.jna.Pointer
E/AndroidRuntime(19100): 	at com.sun.jna.Native.initIDs(Native Method)
E/AndroidRuntime(19100): 	at com.sun.jna.Native.<clinit>(Unknown Source:287)
E/AndroidRuntime(19100): 	at com.sun.jna.n.U(SourceFile:1)
E/AndroidRuntime(19100): 	at com.sun.jna.n.<init>(SourceFile:4)
E/AndroidRuntime(19100): 	at com.sun.jna.n.<init>(SourceFile:3)
E/AndroidRuntime(19100): 	at com.sun.jna.n.<init>(SourceFile:2)
E/AndroidRuntime(19100): 	at com.sun.jna.n.<init>(SourceFile:1)
E/AndroidRuntime(19100): 	at d0.k.<init>(SourceFile:1)
E/AndroidRuntime(19100): 	at d0.g.d(SourceFile:12)
E/AndroidRuntime(19100): 	at tech.threefold.mycelium.MainActivity.R(SourceFile:131)
E/AndroidRuntime(19100): 	at tech.threefold.mycelium.MainActivity.P(SourceFile:1)
E/AndroidRuntime(19100): 	at c0.a.a(SourceFile:1)
E/AndroidRuntime(19100): 	at B.j$a.a(SourceFile:18)
E/AndroidRuntime(19100): 	at t.c.k(SourceFile:19)
E/AndroidRuntime(19100): 	at t.c.l(SourceFile:42)
E/AndroidRuntime(19100): 	at t.c.h(SourceFile:1)
E/AndroidRuntime(19100): 	at t.b.run(SourceFile:1)
E/AndroidRuntime(19100): 	at android.os.Handler.handleCallback(Handler.java:958)
E/AndroidRuntime(19100): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(19100): 	at android.os.Looper.loopOnce(Looper.java:205)
E/AndroidRuntime(19100): 	at android.os.Looper.loop(Looper.java:294)
E/AndroidRuntime(19100): 	at android.app.ActivityThread.main(ActivityThread.java:8177)
E/AndroidRuntime(19100): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(19100): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
E/AndroidRuntime(19100): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
```

**Comment by iwanbk** [comment]
added this to proguard-rule
```
-keep class com.sun.jna.** { *; }
-keepclassmembers class * extends com.sun.jna.Structure {
   public *;
   protected *;
}

-dontwarn java.awt.**
-dontwarn com.sun.jna.Native$AWT%
```
 fixed above error message, but still got error
 ```java
 E/AndroidRuntime(19617): FATAL EXCEPTION: main
E/AndroidRuntime(19617): Process: tech.threefold.mycelium, PID: 19617
E/AndroidRuntime(19617): java.lang.Error: Structure.getFieldOrder() on class f0.h$a does not provide enough names [0] ([]) to match declared fields [3] ([capacity, data, len])
E/AndroidRuntime(19617):        at com.sun.jna.Structure.getFields(Unknown Source:148)
E/AndroidRuntime(19617):        at com.sun.jna.Structure.deriveLayout(Unknown Source:2)
E/AndroidRuntime(19617):        at com.sun.jna.Structure.calculateSize(SourceFile:2)
E/AndroidRuntime(19617):        at com.sun.jna.Structure.allocateMemory(SourceFile:3)
E/AndroidRuntime(19617):        at com.sun.jna.Structure.allocateMemory(SourceFile:1)
E/AndroidRuntime(19617):        at com.sun.jna.Structure.newInstance(SourceFile:1)
E/AndroidRuntime(19617):        at com.sun.jna.Structure.newInstance(SourceFile:3)
E/AndroidRuntime(19617):        at com.sun.jna.Structure.size(SourceFile:3)
E/AndroidRuntime(19617):        at com.sun.jna.Native.getNativeSize(SourceFile:2)
E/AndroidRuntime(19617):        at com.sun.jna.Structure.getNativeSize(SourceFile:2)
E/AndroidRuntime(19617):        at com.sun.jna.Structure.getNativeSize(SourceFile:1)
E/AndroidRuntime(19617):        at com.sun.jna.Structure.validateField(Unknown Source:32)
E/AndroidRuntime(19617):        at com.sun.jna.Structure.validateFields(Unknown Source:28)
E/AndroidRuntime(19617):        at com.sun.jna.Structure.<init>(SourceFile:6)
E/AndroidRuntime(19617):        at com.sun.jna.Structure.<init>(SourceFile:5)
E/AndroidRuntime(19617):        at com.sun.jna.Structure.<init>(SourceFile:2)
E/AndroidRuntime(19617):        at com.sun.jna.Structure.<init>(SourceFile:1)
E/AndroidRuntime(19617):        at f0.k.<init>(SourceFile:1)
E/AndroidRuntime(19617):        at f0.g.d(SourceFile:12)
E/AndroidRuntime(19617):        at tech.threefold.mycelium.MainActivity.R(SourceFile:131)
E/AndroidRuntime(19617):        at tech.threefold.mycelium.MainActivity.P(SourceFile:1)
E/AndroidRuntime(19617):        at e0.a.a(SourceFile:1)
E/AndroidRuntime(19617):        at C.j$a.a(SourceFile:18)
E/AndroidRuntime(19617):        at u.c.k(SourceFile:19)
E/AndroidRuntime(19617):        at u.c.l(SourceFile:42)
E/AndroidRuntime(19617):        at u.c.h(SourceFile:1)
E/AndroidRuntime(19617):        at u.b.run(SourceFile:1)
E/AndroidRuntime(19617):        at android.os.Handler.handleCallback(Handler.java:958)
E/AndroidRuntime(19617):        at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(19617):        at android.os.Looper.loopOnce(Looper.java:205)
E/AndroidRuntime(19617):        at android.os.Looper.loop(Looper.java:294)
E/AndroidRuntime(19617):        at android.app.ActivityThread.main(ActivityThread.java:8177)
E/AndroidRuntime(19617):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(19617):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
E/AndroidRuntime(19617):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
```

**Comment by iwanbk** [comment]
the above issue fixed by adding this in `android/app/build.gradle` in `release` section`
```gradle
minifyEnabled false
shrinkResources false
```
the minify and shrink process causing this issue.
after above fix everything works fine, but the release `.apk` size increased from ~23mb to ~35mb
